[theme]
primaryColor = "#FFD700"
backgroundColor = "#0a0a1a"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
